development:
  adapter: postgresql
  encoding: utf8
  database: discovery_dev
  min_messages: WARNING
  host: 127.0.0.1
  
test:
  adapter: postgresql
  encoding: utf8
  database: discovery_test
  min_messages: WARNING
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: utf8
  database: discovery_prod
  min_messages: WARNING
